name: Generación de Documentación

on:
  pull_request:
    branches:
      - main

jobs:
  generar_documentacion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install openai  # Librería de IA para generar texto
          pip install pylint  # Librería para análisis de código

      - name: Run documentation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Usar el secreto aquí
     
        run: python generar_documentacion.py

